version: "2"

services:
  db:
    container_name: "db"
    image: "mysql:5.6"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=ws_peliculas
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
    volumes:
      - ./dump:/docker-entrypoint-initdb.d/ # init database
    ports:
      - "3306:3306"

  app:
    container_name: "app"
    image: "helloworld-rs"
    depends_on:
      - db
    ports:
      - "8080:8080" # application
      - "9990:9990" # admin console

networks:
    default:
        driver: bridge
